import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
  import { ReduxProvider } from "./redux/component/ReduxProvider";
import WebSocketProvider from "./utils/WebSocketProvider";
import { Toaster } from "react-hot-toast";
import useGlobalAlerts from "./Pages/Components/alerts/useGlobalAlerts";
import GlobalAlertProvider from "./utils/GlobalAlertProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ReduxProvider>
         
         <WebSocketProvider>
         <GlobalAlertProvider>
         {children}
         </GlobalAlertProvider>
         
        
         </WebSocketProvider>
         </ReduxProvider>
         <Toaster/>
      </body>
    </html>
    
  );
}
